spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:oracle:thin:@localhost:1521:xe}
    username: ${JDBC_DATABASE_USERNAME:ORACLEUSR}
    password: ${JDBC_DATABASE_PASSWORD:ORACLEUSR}
    dbcp2:
      max-wait-millis: 30000
      validation-query: SELECT 1
      validation-query-timeout: 30
    type: oracle.ucp.jdbc.PoolDataSource
    oracleucp:
      minPoolSize: 4
      maxPoolSize: 20
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
 